### ISSUE TITLE
No way to disable change tracking?

### ISSUE THREAD

**Issue by sid-6581** [linq2db/linq2db.EntityFrameworkCore#56]
In `LinqToDBForEfTools.cs` there is this code:

```cs
public static bool EnableChangeTracker 
{ 
	get => Implementation.EnableChangeTracker;
	set => Implementation.EnableChangeTracker = true;
}
```

But the default implementation seems to default to true already, so the only way to disable the change tracking seems to be to go through `Implementation.EnableChangeTracker` myself.

I'm also not sure the change tracking is properly disabled when this property is set to true, but `AsNoTracking()` is used on the query. It seems to still track changes in that scenario.

**Comment by sdanyliv** [comment]
Thanks for reporting. Will check and update library tomorrow if I can reproduce this.

**Comment by Shane32** [comment]
Just to confirm, you're saying that it cannot be set to `false`, correct?  Because it always sets to `true` rather than to `value` and it should read:
```csharp
set => Implementation.EnableChangeTracker = value;
```

**Comment by sid-6581** [comment]
That's correct, it can't currently be set to `false` unless you do `Implementation.EnableChangeTracker = false` directly.

The second part of the issue is that it doesn't seem like `AsNoTracking()` is respected when `EnableChangeTracker` is `true`. Basically this is what happens in my situation:

1. Use EF Core directly to load a tracked entity.
2. Use `ToListAsyncLinqToDB()` with `AsNoTracking()` to bulk load some other entities in the same context.
3. Update the entities loaded in 2.
4. Start a transaction.
5. Use LinqToDB to bulk delete all entities from 2, then bulk insert new copies.
6. Update the entity loaded in 1, then use regular EF Core `SaveChangesAsync()` to save changes back.
7. Commit transaction.

What happens is that the entities loaded and updated in 2 and 3 are in the change tracker, and `SaveChangesAsync()` tries to update those entities. That fails with a `DbUpdateConcurrencyException` because those entities no longer exist (they were bulk deleted in 5).

**Comment by Shane32** [comment]
It looks like to me that the `LinqToDBForEFToolsImplDefault.TransformExpression` code runs multiple times when processing a query.  One of those times it will notice the `AsNoTracking()` and set the `LinqToDBForEFToolsDataConnection.Tracking` property to `false`.  But the other times it sets it to `true`, overriding the `false` setting.  I might hazard a guess that the fix is to set it up so `LinqToDBForEFToolsDataConnection.Tracking` is initialized to `true` for every query, and then during expression parsing, only overwrite the property with `false` when it detects `AsNoTracking()`.  This should not affect the `EnableChangeTracker` property, which would still globally disable change tracking.

@sdanyliv I added two failing tests to a branch called `issue_56`, and fixed the broken property (which fixes one of the tests) - you can take it from here.

**Comment by sid-6581** [comment]
Wow, that was quick! I really appreciate that. I wasn't sure if I was missing some intentional behavior, but it didn't seem right.
